---
title: "Resampling + Boostrapping Exercises"
output:
    html_document:
        keep_md: true
---

## Question 1

The bootstrap uses what to estimate the sampling distribution of a statistic?

- The true population distribution
- The empirical distribution that puts probability 1/n for each observed data point **<-- ANSWER**

## Question 2

When performing the bootstrap via Monte Carlo resampling for a dataset of size n, which is true? (Assume that you're going to do 10,000 bootstrap resamples)

- You sample n complete datasets of size 10,000 with replacement
- You sample 10,000 complete datasets of size n without replacement
- You sample 10,000 complete datasets of size n with replacement **<-- ANSWER**
- You sample n complete datasets of size 10,000 without replacement

## Question 3

Permutation tests do what?

- Creates a null distribution for a hypothesis test by permuting a predictor variable **<-- ANSWER**
- Creates a null distribution by resampling from the response with replacement
- Creates an alternative distribution by permuting group labels
- Creates confidence intervals y resampling with replacement